//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="sourceAPPidentity" type="{urn:dmt:custodian2016}TGUID"/&gt;
 *         &lt;element name="cryptedMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "envelope")
public class Envelope {

    @XmlElement(required = true)
    protected String sourceAPPidentity;
    @XmlElement(required = true)
    protected String cryptedMessage;

    /**
     * Gets the value of the sourceAPPidentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceAPPidentity() {
        return sourceAPPidentity;
    }

    /**
     * Sets the value of the sourceAPPidentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceAPPidentity(String value) {
        this.sourceAPPidentity = value;
    }

    /**
     * Gets the value of the cryptedMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCryptedMessage() {
        return cryptedMessage;
    }

    /**
     * Sets the value of the cryptedMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCryptedMessage(String value) {
        this.cryptedMessage = value;
    }

}
