//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * Счет в ЦБ сокращеная версия для выписок
 * 
 * <p>Java class for TAccountSimple complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAccountSimple"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TCustomerSimple"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agreements" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="agreement"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{urn:dmt:custodian2016}TAgreement"&gt;
 *                           &lt;attribute name="changed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="autoGenerate" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="nssmcClientTypeCode"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;urn:dmt:custodian2016&gt;Tnssmc_ClientType"&gt;
 *                 &lt;attribute name="changed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="accountNumber" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *         &lt;element name="State" type="{urn:dmt:custodian2016}TAccountState"/&gt;
 *         &lt;element name="Status" type="{urn:dmt:custodian2016}TAccountStatus"/&gt;
 *         &lt;element name="accountDateopen" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="accountDateClose" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="CoOwners" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="CoOwner" type="{urn:dmt:custodian2016}TCustomerSimple"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Level" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="NDU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                   &lt;element name="NBU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NBU" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="deponent_id" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="BaseAggregated_id" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AccountID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAccountSimple", propOrder = {
    "agreements",
    "nssmcClientTypeCode",
    "accountNumber",
    "state",
    "status",
    "accountDateopen",
    "accountDateClose",
    "coOwners",
    "level",
    "nbu",
    "accountID"
})
@XmlSeeAlso({
    TAccountListV2RowStandart.class
})
public class TAccountSimple
    extends TCustomerSimple
{

    protected TAccountSimple.Agreements agreements;
    @XmlElement(required = true)
    protected TAccountSimple.NssmcClientTypeCode nssmcClientTypeCode;
    @XmlElement(required = true)
    protected String accountNumber;
    @XmlElement(name = "State", required = true)
    protected BigInteger state;
    @XmlElement(name = "Status", required = true)
    protected BigInteger status;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accountDateopen;
    protected Object accountDateClose;
    @XmlElement(name = "CoOwners")
    protected TAccountSimple.CoOwners coOwners;
    @XmlElement(name = "Level")
    protected TAccountSimple.Level level;
    @XmlElement(name = "NBU")
    protected TAccountSimple.NBU nbu;
    @XmlElement(name = "AccountID", required = true)
    protected BigInteger accountID;

    /**
     * Gets the value of the agreements property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountSimple.Agreements }
     *     
     */
    public TAccountSimple.Agreements getAgreements() {
        return agreements;
    }

    /**
     * Sets the value of the agreements property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountSimple.Agreements }
     *     
     */
    public void setAgreements(TAccountSimple.Agreements value) {
        this.agreements = value;
    }

    /**
     * Gets the value of the nssmcClientTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountSimple.NssmcClientTypeCode }
     *     
     */
    public TAccountSimple.NssmcClientTypeCode getNssmcClientTypeCode() {
        return nssmcClientTypeCode;
    }

    /**
     * Sets the value of the nssmcClientTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountSimple.NssmcClientTypeCode }
     *     
     */
    public void setNssmcClientTypeCode(TAccountSimple.NssmcClientTypeCode value) {
        this.nssmcClientTypeCode = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setState(BigInteger value) {
        this.state = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStatus(BigInteger value) {
        this.status = value;
    }

    /**
     * Gets the value of the accountDateopen property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccountDateopen() {
        return accountDateopen;
    }

    /**
     * Sets the value of the accountDateopen property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccountDateopen(XMLGregorianCalendar value) {
        this.accountDateopen = value;
    }

    /**
     * Gets the value of the accountDateClose property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAccountDateClose() {
        return accountDateClose;
    }

    /**
     * Sets the value of the accountDateClose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAccountDateClose(Object value) {
        this.accountDateClose = value;
    }

    /**
     * Gets the value of the coOwners property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountSimple.CoOwners }
     *     
     */
    public TAccountSimple.CoOwners getCoOwners() {
        return coOwners;
    }

    /**
     * Sets the value of the coOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountSimple.CoOwners }
     *     
     */
    public void setCoOwners(TAccountSimple.CoOwners value) {
        this.coOwners = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountSimple.Level }
     *     
     */
    public TAccountSimple.Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountSimple.Level }
     *     
     */
    public void setLevel(TAccountSimple.Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the nbu property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountSimple.NBU }
     *     
     */
    public TAccountSimple.NBU getNBU() {
        return nbu;
    }

    /**
     * Sets the value of the nbu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountSimple.NBU }
     *     
     */
    public void setNBU(TAccountSimple.NBU value) {
        this.nbu = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountID(BigInteger value) {
        this.accountID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="agreement"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{urn:dmt:custodian2016}TAgreement"&gt;
     *                 &lt;attribute name="changed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="autoGenerate" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agreement"
    })
    public static class Agreements {

        protected List<TAccountSimple.Agreements.Agreement> agreement;
        @XmlAttribute(name = "autoGenerate")
        protected Boolean autoGenerate;

        /**
         * Gets the value of the agreement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the agreement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAgreement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TAccountSimple.Agreements.Agreement }
         * 
         * 
         */
        public List<TAccountSimple.Agreements.Agreement> getAgreement() {
            if (agreement == null) {
                agreement = new ArrayList<TAccountSimple.Agreements.Agreement>();
            }
            return this.agreement;
        }

        /**
         * Gets the value of the autoGenerate property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAutoGenerate() {
            return autoGenerate;
        }

        /**
         * Sets the value of the autoGenerate property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAutoGenerate(Boolean value) {
            this.autoGenerate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{urn:dmt:custodian2016}TAgreement"&gt;
         *       &lt;attribute name="changed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Agreement
            extends TAgreement
        {

            @XmlAttribute(name = "changed")
            protected Boolean changed;

            /**
             * Gets the value of the changed property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isChanged() {
                return changed;
            }

            /**
             * Sets the value of the changed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setChanged(Boolean value) {
                this.changed = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="CoOwner" type="{urn:dmt:custodian2016}TCustomerSimple"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "coOwner"
    })
    public static class CoOwners {

        @XmlElement(name = "CoOwner")
        protected List<TCustomerSimple> coOwner;

        /**
         * Gets the value of the coOwner property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the coOwner property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCoOwner().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TCustomerSimple }
         * 
         * 
         */
        public List<TCustomerSimple> getCoOwner() {
            if (coOwner == null) {
                coOwner = new ArrayList<TCustomerSimple>();
            }
            return this.coOwner;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="NDU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *         &lt;element name="NBU" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ndu",
        "nbu"
    })
    public static class Level {

        @XmlElement(name = "NDU", required = true)
        protected Object ndu;
        @XmlElement(name = "NBU", required = true)
        protected Object nbu;

        /**
         * Gets the value of the ndu property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNDU() {
            return ndu;
        }

        /**
         * Sets the value of the ndu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNDU(Object value) {
            this.ndu = value;
        }

        /**
         * Gets the value of the nbu property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getNBU() {
            return nbu;
        }

        /**
         * Sets the value of the nbu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setNBU(Object value) {
            this.nbu = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="deponent_id" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="BaseAggregated_id" type="{urn:dmt:custodian2016}TAgregateAccountID" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deponentId",
        "baseAggregatedId"
    })
    public static class NBU {

        @XmlElement(name = "deponent_id")
        protected Object deponentId;
        @XmlElement(name = "BaseAggregated_id")
        protected String baseAggregatedId;

        /**
         * Gets the value of the deponentId property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDeponentId() {
            return deponentId;
        }

        /**
         * Sets the value of the deponentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDeponentId(Object value) {
            this.deponentId = value;
        }

        /**
         * Gets the value of the baseAggregatedId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseAggregatedId() {
            return baseAggregatedId;
        }

        /**
         * Sets the value of the baseAggregatedId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseAggregatedId(String value) {
            this.baseAggregatedId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;urn:dmt:custodian2016&gt;Tnssmc_ClientType"&gt;
     *       &lt;attribute name="changed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NssmcClientTypeCode {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "changed")
        protected Boolean changed;

        /**
         *  37. Довідник «Види депонентів, клієнтів депозитарної установи, клієнтів торговця цінними паперами»
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the changed property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isChanged() {
            return changed;
        }

        /**
         * Sets the value of the changed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setChanged(Boolean value) {
            this.changed = value;
        }

    }

}
