//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Тело запроса
 * 
 * <p>Java class for TbodyRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TbodyRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Customer" type="{urn:dmt:custodian2016}TCustomer"/&gt;
 *         &lt;element name="newAccount" type="{urn:dmt:custodian2016}TnewAccountRequest"/&gt;
 *         &lt;element name="updateCustomer" type="{urn:dmt:custodian2016}TupdateCustomer"/&gt;
 *         &lt;element name="updateAccount" type="{urn:dmt:custodian2016}TupdateAccount"/&gt;
 *         &lt;element name="SearchCustomer" type="{urn:dmt:custodian2016}TSearchCustomer"/&gt;
 *         &lt;element name="SearchAccount" type="{urn:dmt:custodian2016}TSearchAccount"/&gt;
 *         &lt;element name="SearchAccountV2" type="{urn:dmt:custodian2016}TSearchAccountV2"/&gt;
 *         &lt;element name="Statement_of_Holdings_Request" type="{urn:dmt:custodian2016}TStatement_of_Holdings_Request"/&gt;
 *         &lt;element name="Statement_of_Transactions_Request" type="{urn:dmt:custodian2016}TStatement_of_Transactions_Request"/&gt;
 *         &lt;element name="Balance" type="{urn:dmt:custodian2016}TBalance_request"/&gt;
 *         &lt;element name="Transaction" type="{urn:dmt:custodian2016}TTransaction_request"/&gt;
 *         &lt;element name="Transaction_pre_check" type="{urn:dmt:custodian2016}TTransaction_pre_check_request"/&gt;
 *         &lt;element name="TransactionCommit" type="{urn:dmt:custodian2016}TTransactionCommit"/&gt;
 *         &lt;element name="TransactionRollback" type="{urn:dmt:custodian2016}TTransactionRollback"/&gt;
 *         &lt;element name="Dictionaries" type="{urn:dmt:custodian2016}TDummy"/&gt;
 *         &lt;element name="Dictionary" type="{urn:dmt:custodian2016}TDictionaryCustom_request"/&gt;
 *         &lt;element name="QueueList" type="{urn:dmt:custodian2016}TDummy"/&gt;
 *         &lt;element name="QueueEntry" type="{urn:dmt:custodian2016}TQueueRequest"/&gt;
 *         &lt;element name="limit" type="{urn:dmt:custodian2016}Tlimit"/&gt;
 *         &lt;element name="limitList" type="{urn:dmt:custodian2016}TDummy"/&gt;
 *         &lt;element name="fiList" type="{urn:dmt:custodian2016}TDummy"/&gt;
 *         &lt;element name="InvoiceSearch" type="{urn:dmt:custodian2016}TInvoiceSearch"/&gt;
 *         &lt;element name="AccountNum" type="{urn:dmt:custodian2016}TAccountNumRequest"/&gt;
 *         &lt;element name="PaymentList" type="{urn:dmt:custodian2016}TPaymentList"/&gt;
 *         &lt;element name="AccountNumReserveCancel" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *         &lt;element name="PenaltyList" type="{urn:dmt:custodian2016}TPenaltyList"/&gt;
 *         &lt;element name="Transaction_Reversal" type="{urn:dmt:custodian2016}TTransaction_request_Reversal"/&gt;
 *         &lt;element name="FI" type="{urn:dmt:custodian2016}TFI"/&gt;
 *         &lt;element name="getFI"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ISIN" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;length value="12"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Depositary" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{urn:dmt:custodian2016}TDepositary"&gt;
 *                         &lt;length value="4"/&gt;
 *                         &lt;enumeration value="100"/&gt;
 *                         &lt;enumeration value="200"/&gt;
 *                         &lt;enumeration value="1000"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Transaction_stockBlock" type="{urn:dmt:custodian2016}TTransaction_request_stockBlock"/&gt;
 *         &lt;element name="Balance_compare" type="{urn:dmt:custodian2016}TBalance_compare_request"/&gt;
 *         &lt;element name="invoice_send_to_abs" type="{urn:dmt:custodian2016}Tinvoice_send_to_abs_Done"/&gt;
 *         &lt;element name="IncomeSearch" type="{urn:dmt:custodian2016}TIncomeSearch"/&gt;
 *         &lt;element name="Income_send_to_abs" type="{urn:dmt:custodian2016}TIncome_send_to_abs_Done"/&gt;
 *         &lt;element name="Account"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Income_payout_rollback" type="{urn:dmt:custodian2016}TIncome_payout_rollback"/&gt;
 *         &lt;element name="CustomReport" type="{urn:dmt:custodian2016}TCustomReport_request"/&gt;
 *         &lt;element name="CustomReportParam" type="{urn:dmt:custodian2016}TCustomReportParams_request"/&gt;
 *         &lt;element name="CustomReportList" type="{urn:dmt:custodian2016}TDummy"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TbodyRequest", propOrder = {
    "customer",
    "newAccount",
    "updateCustomer",
    "updateAccount",
    "searchCustomer",
    "searchAccount",
    "searchAccountV2",
    "statementOfHoldingsRequest",
    "statementOfTransactionsRequest",
    "balance",
    "transaction",
    "transactionPreCheck",
    "transactionCommit",
    "transactionRollback",
    "dictionaries",
    "dictionary",
    "queueList",
    "queueEntry",
    "limit",
    "limitList",
    "fiList",
    "invoiceSearch",
    "accountNum",
    "paymentList",
    "accountNumReserveCancel",
    "penaltyList",
    "transactionReversal",
    "fi",
    "getFI",
    "transactionStockBlock",
    "balanceCompare",
    "invoiceSendToAbs",
    "incomeSearch",
    "incomeSendToAbs",
    "account",
    "incomePayoutRollback",
    "customReport",
    "customReportParam",
    "customReportList"
})
public class TbodyRequest {

    @XmlElement(name = "Customer")
    protected TCustomer customer;
    protected TnewAccountRequest newAccount;
    protected TupdateCustomer updateCustomer;
    protected TupdateAccount updateAccount;
    @XmlElement(name = "SearchCustomer")
    protected TSearchCustomer searchCustomer;
    @XmlElement(name = "SearchAccount")
    protected TSearchAccount searchAccount;
    @XmlElement(name = "SearchAccountV2")
    protected TSearchAccountV2 searchAccountV2;
    @XmlElement(name = "Statement_of_Holdings_Request")
    protected TStatementOfHoldingsRequest statementOfHoldingsRequest;
    @XmlElement(name = "Statement_of_Transactions_Request")
    protected TStatementOfTransactionsRequest statementOfTransactionsRequest;
    @XmlElement(name = "Balance")
    protected TBalanceRequest balance;
    @XmlElement(name = "Transaction")
    protected TTransactionRequest transaction;
    @XmlElement(name = "Transaction_pre_check")
    protected TTransactionPreCheckRequest transactionPreCheck;
    @XmlElement(name = "TransactionCommit")
    protected TTransactionCommit transactionCommit;
    @XmlElement(name = "TransactionRollback")
    protected TTransactionRollback transactionRollback;
    @XmlElement(name = "Dictionaries")
    protected TDummy dictionaries;
    @XmlElement(name = "Dictionary")
    protected TDictionaryCustomRequest dictionary;
    @XmlElement(name = "QueueList")
    protected TDummy queueList;
    @XmlElement(name = "QueueEntry")
    protected TQueueRequest queueEntry;
    protected Tlimit limit;
    protected TDummy limitList;
    protected TDummy fiList;
    @XmlElement(name = "InvoiceSearch")
    protected TInvoiceSearch invoiceSearch;
    @XmlElement(name = "AccountNum")
    protected TAccountNumRequest accountNum;
    @XmlElement(name = "PaymentList")
    protected TPaymentList paymentList;
    @XmlElement(name = "AccountNumReserveCancel")
    protected String accountNumReserveCancel;
    @XmlElement(name = "PenaltyList")
    protected TPenaltyList penaltyList;
    @XmlElement(name = "Transaction_Reversal")
    protected TTransactionRequestReversal transactionReversal;
    @XmlElement(name = "FI")
    protected TFI fi;
    protected TbodyRequest.GetFI getFI;
    @XmlElement(name = "Transaction_stockBlock")
    protected TTransactionRequestStockBlock transactionStockBlock;
    @XmlElement(name = "Balance_compare")
    protected TBalanceCompareRequest balanceCompare;
    @XmlElement(name = "invoice_send_to_abs")
    protected TinvoiceSendToAbsDone invoiceSendToAbs;
    @XmlElement(name = "IncomeSearch")
    protected TIncomeSearch incomeSearch;
    @XmlElement(name = "Income_send_to_abs")
    protected TIncomeSendToAbsDone incomeSendToAbs;
    @XmlElement(name = "Account")
    protected TbodyRequest.Account account;
    @XmlElement(name = "Income_payout_rollback")
    protected TIncomePayoutRollback incomePayoutRollback;
    @XmlElement(name = "CustomReport")
    protected TCustomReportRequest customReport;
    @XmlElement(name = "CustomReportParam")
    protected TCustomReportParamsRequest customReportParam;
    @XmlElement(name = "CustomReportList")
    protected TDummy customReportList;

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link TCustomer }
     *     
     */
    public TCustomer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCustomer }
     *     
     */
    public void setCustomer(TCustomer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the newAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TnewAccountRequest }
     *     
     */
    public TnewAccountRequest getNewAccount() {
        return newAccount;
    }

    /**
     * Sets the value of the newAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TnewAccountRequest }
     *     
     */
    public void setNewAccount(TnewAccountRequest value) {
        this.newAccount = value;
    }

    /**
     * Gets the value of the updateCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link TupdateCustomer }
     *     
     */
    public TupdateCustomer getUpdateCustomer() {
        return updateCustomer;
    }

    /**
     * Sets the value of the updateCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TupdateCustomer }
     *     
     */
    public void setUpdateCustomer(TupdateCustomer value) {
        this.updateCustomer = value;
    }

    /**
     * Gets the value of the updateAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TupdateAccount }
     *     
     */
    public TupdateAccount getUpdateAccount() {
        return updateAccount;
    }

    /**
     * Sets the value of the updateAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TupdateAccount }
     *     
     */
    public void setUpdateAccount(TupdateAccount value) {
        this.updateAccount = value;
    }

    /**
     * Gets the value of the searchCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link TSearchCustomer }
     *     
     */
    public TSearchCustomer getSearchCustomer() {
        return searchCustomer;
    }

    /**
     * Sets the value of the searchCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSearchCustomer }
     *     
     */
    public void setSearchCustomer(TSearchCustomer value) {
        this.searchCustomer = value;
    }

    /**
     * Gets the value of the searchAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TSearchAccount }
     *     
     */
    public TSearchAccount getSearchAccount() {
        return searchAccount;
    }

    /**
     * Sets the value of the searchAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSearchAccount }
     *     
     */
    public void setSearchAccount(TSearchAccount value) {
        this.searchAccount = value;
    }

    /**
     * Gets the value of the searchAccountV2 property.
     * 
     * @return
     *     possible object is
     *     {@link TSearchAccountV2 }
     *     
     */
    public TSearchAccountV2 getSearchAccountV2() {
        return searchAccountV2;
    }

    /**
     * Sets the value of the searchAccountV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSearchAccountV2 }
     *     
     */
    public void setSearchAccountV2(TSearchAccountV2 value) {
        this.searchAccountV2 = value;
    }

    /**
     * Gets the value of the statementOfHoldingsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TStatementOfHoldingsRequest }
     *     
     */
    public TStatementOfHoldingsRequest getStatementOfHoldingsRequest() {
        return statementOfHoldingsRequest;
    }

    /**
     * Sets the value of the statementOfHoldingsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatementOfHoldingsRequest }
     *     
     */
    public void setStatementOfHoldingsRequest(TStatementOfHoldingsRequest value) {
        this.statementOfHoldingsRequest = value;
    }

    /**
     * Gets the value of the statementOfTransactionsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TStatementOfTransactionsRequest }
     *     
     */
    public TStatementOfTransactionsRequest getStatementOfTransactionsRequest() {
        return statementOfTransactionsRequest;
    }

    /**
     * Sets the value of the statementOfTransactionsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatementOfTransactionsRequest }
     *     
     */
    public void setStatementOfTransactionsRequest(TStatementOfTransactionsRequest value) {
        this.statementOfTransactionsRequest = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link TBalanceRequest }
     *     
     */
    public TBalanceRequest getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBalanceRequest }
     *     
     */
    public void setBalance(TBalanceRequest value) {
        this.balance = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRequest }
     *     
     */
    public TTransactionRequest getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRequest }
     *     
     */
    public void setTransaction(TTransactionRequest value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the transactionPreCheck property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionPreCheckRequest }
     *     
     */
    public TTransactionPreCheckRequest getTransactionPreCheck() {
        return transactionPreCheck;
    }

    /**
     * Sets the value of the transactionPreCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionPreCheckRequest }
     *     
     */
    public void setTransactionPreCheck(TTransactionPreCheckRequest value) {
        this.transactionPreCheck = value;
    }

    /**
     * Gets the value of the transactionCommit property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionCommit }
     *     
     */
    public TTransactionCommit getTransactionCommit() {
        return transactionCommit;
    }

    /**
     * Sets the value of the transactionCommit property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionCommit }
     *     
     */
    public void setTransactionCommit(TTransactionCommit value) {
        this.transactionCommit = value;
    }

    /**
     * Gets the value of the transactionRollback property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRollback }
     *     
     */
    public TTransactionRollback getTransactionRollback() {
        return transactionRollback;
    }

    /**
     * Sets the value of the transactionRollback property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRollback }
     *     
     */
    public void setTransactionRollback(TTransactionRollback value) {
        this.transactionRollback = value;
    }

    /**
     * Gets the value of the dictionaries property.
     * 
     * @return
     *     possible object is
     *     {@link TDummy }
     *     
     */
    public TDummy getDictionaries() {
        return dictionaries;
    }

    /**
     * Sets the value of the dictionaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDummy }
     *     
     */
    public void setDictionaries(TDummy value) {
        this.dictionaries = value;
    }

    /**
     * Gets the value of the dictionary property.
     * 
     * @return
     *     possible object is
     *     {@link TDictionaryCustomRequest }
     *     
     */
    public TDictionaryCustomRequest getDictionary() {
        return dictionary;
    }

    /**
     * Sets the value of the dictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDictionaryCustomRequest }
     *     
     */
    public void setDictionary(TDictionaryCustomRequest value) {
        this.dictionary = value;
    }

    /**
     * Gets the value of the queueList property.
     * 
     * @return
     *     possible object is
     *     {@link TDummy }
     *     
     */
    public TDummy getQueueList() {
        return queueList;
    }

    /**
     * Sets the value of the queueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDummy }
     *     
     */
    public void setQueueList(TDummy value) {
        this.queueList = value;
    }

    /**
     * Gets the value of the queueEntry property.
     * 
     * @return
     *     possible object is
     *     {@link TQueueRequest }
     *     
     */
    public TQueueRequest getQueueEntry() {
        return queueEntry;
    }

    /**
     * Sets the value of the queueEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link TQueueRequest }
     *     
     */
    public void setQueueEntry(TQueueRequest value) {
        this.queueEntry = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link Tlimit }
     *     
     */
    public Tlimit getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tlimit }
     *     
     */
    public void setLimit(Tlimit value) {
        this.limit = value;
    }

    /**
     * Gets the value of the limitList property.
     * 
     * @return
     *     possible object is
     *     {@link TDummy }
     *     
     */
    public TDummy getLimitList() {
        return limitList;
    }

    /**
     * Sets the value of the limitList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDummy }
     *     
     */
    public void setLimitList(TDummy value) {
        this.limitList = value;
    }

    /**
     * Gets the value of the fiList property.
     * 
     * @return
     *     possible object is
     *     {@link TDummy }
     *     
     */
    public TDummy getFiList() {
        return fiList;
    }

    /**
     * Sets the value of the fiList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDummy }
     *     
     */
    public void setFiList(TDummy value) {
        this.fiList = value;
    }

    /**
     * Gets the value of the invoiceSearch property.
     * 
     * @return
     *     possible object is
     *     {@link TInvoiceSearch }
     *     
     */
    public TInvoiceSearch getInvoiceSearch() {
        return invoiceSearch;
    }

    /**
     * Sets the value of the invoiceSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link TInvoiceSearch }
     *     
     */
    public void setInvoiceSearch(TInvoiceSearch value) {
        this.invoiceSearch = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountNumRequest }
     *     
     */
    public TAccountNumRequest getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountNumRequest }
     *     
     */
    public void setAccountNum(TAccountNumRequest value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the paymentList property.
     * 
     * @return
     *     possible object is
     *     {@link TPaymentList }
     *     
     */
    public TPaymentList getPaymentList() {
        return paymentList;
    }

    /**
     * Sets the value of the paymentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPaymentList }
     *     
     */
    public void setPaymentList(TPaymentList value) {
        this.paymentList = value;
    }

    /**
     * Gets the value of the accountNumReserveCancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumReserveCancel() {
        return accountNumReserveCancel;
    }

    /**
     * Sets the value of the accountNumReserveCancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumReserveCancel(String value) {
        this.accountNumReserveCancel = value;
    }

    /**
     * Gets the value of the penaltyList property.
     * 
     * @return
     *     possible object is
     *     {@link TPenaltyList }
     *     
     */
    public TPenaltyList getPenaltyList() {
        return penaltyList;
    }

    /**
     * Sets the value of the penaltyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPenaltyList }
     *     
     */
    public void setPenaltyList(TPenaltyList value) {
        this.penaltyList = value;
    }

    /**
     * Gets the value of the transactionReversal property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRequestReversal }
     *     
     */
    public TTransactionRequestReversal getTransactionReversal() {
        return transactionReversal;
    }

    /**
     * Sets the value of the transactionReversal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRequestReversal }
     *     
     */
    public void setTransactionReversal(TTransactionRequestReversal value) {
        this.transactionReversal = value;
    }

    /**
     * Gets the value of the fi property.
     * 
     * @return
     *     possible object is
     *     {@link TFI }
     *     
     */
    public TFI getFI() {
        return fi;
    }

    /**
     * Sets the value of the fi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFI }
     *     
     */
    public void setFI(TFI value) {
        this.fi = value;
    }

    /**
     * Gets the value of the getFI property.
     * 
     * @return
     *     possible object is
     *     {@link TbodyRequest.GetFI }
     *     
     */
    public TbodyRequest.GetFI getGetFI() {
        return getFI;
    }

    /**
     * Sets the value of the getFI property.
     * 
     * @param value
     *     allowed object is
     *     {@link TbodyRequest.GetFI }
     *     
     */
    public void setGetFI(TbodyRequest.GetFI value) {
        this.getFI = value;
    }

    /**
     * Gets the value of the transactionStockBlock property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRequestStockBlock }
     *     
     */
    public TTransactionRequestStockBlock getTransactionStockBlock() {
        return transactionStockBlock;
    }

    /**
     * Sets the value of the transactionStockBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRequestStockBlock }
     *     
     */
    public void setTransactionStockBlock(TTransactionRequestStockBlock value) {
        this.transactionStockBlock = value;
    }

    /**
     * Gets the value of the balanceCompare property.
     * 
     * @return
     *     possible object is
     *     {@link TBalanceCompareRequest }
     *     
     */
    public TBalanceCompareRequest getBalanceCompare() {
        return balanceCompare;
    }

    /**
     * Sets the value of the balanceCompare property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBalanceCompareRequest }
     *     
     */
    public void setBalanceCompare(TBalanceCompareRequest value) {
        this.balanceCompare = value;
    }

    /**
     * Gets the value of the invoiceSendToAbs property.
     * 
     * @return
     *     possible object is
     *     {@link TinvoiceSendToAbsDone }
     *     
     */
    public TinvoiceSendToAbsDone getInvoiceSendToAbs() {
        return invoiceSendToAbs;
    }

    /**
     * Sets the value of the invoiceSendToAbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TinvoiceSendToAbsDone }
     *     
     */
    public void setInvoiceSendToAbs(TinvoiceSendToAbsDone value) {
        this.invoiceSendToAbs = value;
    }

    /**
     * Gets the value of the incomeSearch property.
     * 
     * @return
     *     possible object is
     *     {@link TIncomeSearch }
     *     
     */
    public TIncomeSearch getIncomeSearch() {
        return incomeSearch;
    }

    /**
     * Sets the value of the incomeSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIncomeSearch }
     *     
     */
    public void setIncomeSearch(TIncomeSearch value) {
        this.incomeSearch = value;
    }

    /**
     * Gets the value of the incomeSendToAbs property.
     * 
     * @return
     *     possible object is
     *     {@link TIncomeSendToAbsDone }
     *     
     */
    public TIncomeSendToAbsDone getIncomeSendToAbs() {
        return incomeSendToAbs;
    }

    /**
     * Sets the value of the incomeSendToAbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIncomeSendToAbsDone }
     *     
     */
    public void setIncomeSendToAbs(TIncomeSendToAbsDone value) {
        this.incomeSendToAbs = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link TbodyRequest.Account }
     *     
     */
    public TbodyRequest.Account getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link TbodyRequest.Account }
     *     
     */
    public void setAccount(TbodyRequest.Account value) {
        this.account = value;
    }

    /**
     * Gets the value of the incomePayoutRollback property.
     * 
     * @return
     *     possible object is
     *     {@link TIncomePayoutRollback }
     *     
     */
    public TIncomePayoutRollback getIncomePayoutRollback() {
        return incomePayoutRollback;
    }

    /**
     * Sets the value of the incomePayoutRollback property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIncomePayoutRollback }
     *     
     */
    public void setIncomePayoutRollback(TIncomePayoutRollback value) {
        this.incomePayoutRollback = value;
    }

    /**
     * Gets the value of the customReport property.
     * 
     * @return
     *     possible object is
     *     {@link TCustomReportRequest }
     *     
     */
    public TCustomReportRequest getCustomReport() {
        return customReport;
    }

    /**
     * Sets the value of the customReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCustomReportRequest }
     *     
     */
    public void setCustomReport(TCustomReportRequest value) {
        this.customReport = value;
    }

    /**
     * Gets the value of the customReportParam property.
     * 
     * @return
     *     possible object is
     *     {@link TCustomReportParamsRequest }
     *     
     */
    public TCustomReportParamsRequest getCustomReportParam() {
        return customReportParam;
    }

    /**
     * Sets the value of the customReportParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCustomReportParamsRequest }
     *     
     */
    public void setCustomReportParam(TCustomReportParamsRequest value) {
        this.customReportParam = value;
    }

    /**
     * Gets the value of the customReportList property.
     * 
     * @return
     *     possible object is
     *     {@link TDummy }
     *     
     */
    public TDummy getCustomReportList() {
        return customReportList;
    }

    /**
     * Sets the value of the customReportList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDummy }
     *     
     */
    public void setCustomReportList(TDummy value) {
        this.customReportList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Account" type="{urn:dmt:custodian2016}TAccount_Num"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class Account {

        @XmlElement(name = "Account", required = true)
        protected String account;

        /**
         * Gets the value of the account property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccount() {
            return account;
        }

        /**
         * Sets the value of the account property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccount(String value) {
            this.account = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ISIN" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;length value="12"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Depositary" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{urn:dmt:custodian2016}TDepositary"&gt;
     *               &lt;length value="4"/&gt;
     *               &lt;enumeration value="100"/&gt;
     *               &lt;enumeration value="200"/&gt;
     *               &lt;enumeration value="1000"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isin",
        "depositary"
    })
    public static class GetFI {

        @XmlElement(name = "ISIN")
        protected String isin;
        @XmlElement(name = "Depositary")
        protected String depositary;

        /**
         * Gets the value of the isin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getISIN() {
            return isin;
        }

        /**
         * Sets the value of the isin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setISIN(String value) {
            this.isin = value;
        }

        /**
         * Gets the value of the depositary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepositary() {
            return depositary;
        }

        /**
         * Sets the value of the depositary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepositary(String value) {
            this.depositary = value;
        }

    }

}
