//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TMoneyTransactionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TMoneyTransactionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TAX"/&gt;
 *     &lt;enumeration value="INCOME"/&gt;
 *     &lt;enumeration value="INTERNAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TMoneyTransactionType")
@XmlEnum
public enum TMoneyTransactionType {


    /**
     * Удержания налогов с выплаты доходов
     *                     
     * 
     */
    TAX,

    /**
     * Выплата доходов
     * 
     */
    INCOME,

    /**
     * Внутрение перемещения денежных средств по балансовым счетам (такие как 3578 и т.д)
     * 
     */
    INTERNAL;

    public String value() {
        return name();
    }

    public static TMoneyTransactionType fromValue(String v) {
        return valueOf(v);
    }

}
