//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TNotificationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TNotificationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="newAccount"/&gt;
 *     &lt;enumeration value="changeAccount"/&gt;
 *     &lt;enumeration value="newTransaction"/&gt;
 *     &lt;enumeration value="connectionState"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TNotificationType")
@XmlEnum
public enum TNotificationType {

    @XmlEnumValue("newAccount")
    NEW_ACCOUNT("newAccount"),
    @XmlEnumValue("changeAccount")
    CHANGE_ACCOUNT("changeAccount"),
    @XmlEnumValue("newTransaction")
    NEW_TRANSACTION("newTransaction"),
    @XmlEnumValue("connectionState")
    CONNECTION_STATE("connectionState");
    private final String value;

    TNotificationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TNotificationType fromValue(String v) {
        for (TNotificationType c: TNotificationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
