//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Выписка про состояние счета
 * 
 * <p>Java class for TStatement_of_Transactions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TStatement_of_Transactions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Account" type="{urn:dmt:custodian2016}TAccountSimple"/&gt;
 *         &lt;element name="Rows" type="{urn:dmt:custodian2016}TStatement_of_Transaction_ISINs_abstract"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStatement_of_Transactions", propOrder = {
    "account",
    "rows"
})
public class TStatementOfTransactions {

    @XmlElement(name = "Account", required = true)
    protected TAccountSimple account;
    @XmlElement(name = "Rows", required = true)
    protected TStatementOfTransactionISINsAbstract rows;

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link TAccountSimple }
     *     
     */
    public TAccountSimple getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAccountSimple }
     *     
     */
    public void setAccount(TAccountSimple value) {
        this.account = value;
    }

    /**
     * Gets the value of the rows property.
     * 
     * @return
     *     possible object is
     *     {@link TStatementOfTransactionISINsAbstract }
     *     
     */
    public TStatementOfTransactionISINsAbstract getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatementOfTransactionISINsAbstract }
     *     
     */
    public void setRows(TStatementOfTransactionISINsAbstract value) {
        this.rows = value;
    }

}
