//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Транзакция - статус транзакции. Пакеты такого класса будут отправляться системой при каждом изменении статуса
 * 
 * <p>Java class for TTransaction_responce complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTransaction_responce"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:dmt:custodian2016}TTransactionHeader_responce"&gt;
 *       &lt;sequence minOccurs="0"&gt;
 *         &lt;element name="request" type="{urn:dmt:custodian2016}TTransaction_request" minOccurs="0"/&gt;
 *         &lt;element name="Statement_of_Holdings" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ParticipantSource" type="{urn:dmt:custodian2016}TStatement_of_Holding" minOccurs="0"/&gt;
 *                   &lt;element name="ParticipantDestination" type="{urn:dmt:custodian2016}TStatement_of_Holding" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Statement_of_Transactions" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ParticipantSource" type="{urn:dmt:custodian2016}TStatement_of_Transactions" minOccurs="0"/&gt;
 *                   &lt;element name="ParticipantDestination" type="{urn:dmt:custodian2016}TStatement_of_Transactions" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTransaction_responce", propOrder = {
    "request",
    "statementOfHoldings",
    "statementOfTransactions"
})
public class TTransactionResponce
    extends TTransactionHeaderResponce
{

    protected TTransactionRequest request;
    @XmlElement(name = "Statement_of_Holdings")
    protected TTransactionResponce.StatementOfHoldings statementOfHoldings;
    @XmlElement(name = "Statement_of_Transactions")
    protected TTransactionResponce.StatementOfTransactions statementOfTransactions;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRequest }
     *     
     */
    public TTransactionRequest getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRequest }
     *     
     */
    public void setRequest(TTransactionRequest value) {
        this.request = value;
    }

    /**
     * Gets the value of the statementOfHoldings property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionResponce.StatementOfHoldings }
     *     
     */
    public TTransactionResponce.StatementOfHoldings getStatementOfHoldings() {
        return statementOfHoldings;
    }

    /**
     * Sets the value of the statementOfHoldings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionResponce.StatementOfHoldings }
     *     
     */
    public void setStatementOfHoldings(TTransactionResponce.StatementOfHoldings value) {
        this.statementOfHoldings = value;
    }

    /**
     * Gets the value of the statementOfTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionResponce.StatementOfTransactions }
     *     
     */
    public TTransactionResponce.StatementOfTransactions getStatementOfTransactions() {
        return statementOfTransactions;
    }

    /**
     * Sets the value of the statementOfTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionResponce.StatementOfTransactions }
     *     
     */
    public void setStatementOfTransactions(TTransactionResponce.StatementOfTransactions value) {
        this.statementOfTransactions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ParticipantSource" type="{urn:dmt:custodian2016}TStatement_of_Holding" minOccurs="0"/&gt;
     *         &lt;element name="ParticipantDestination" type="{urn:dmt:custodian2016}TStatement_of_Holding" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participantSource",
        "participantDestination"
    })
    public static class StatementOfHoldings {

        @XmlElement(name = "ParticipantSource")
        protected TStatementOfHolding participantSource;
        @XmlElement(name = "ParticipantDestination")
        protected TStatementOfHolding participantDestination;

        /**
         * Gets the value of the participantSource property.
         * 
         * @return
         *     possible object is
         *     {@link TStatementOfHolding }
         *     
         */
        public TStatementOfHolding getParticipantSource() {
            return participantSource;
        }

        /**
         * Sets the value of the participantSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link TStatementOfHolding }
         *     
         */
        public void setParticipantSource(TStatementOfHolding value) {
            this.participantSource = value;
        }

        /**
         * Gets the value of the participantDestination property.
         * 
         * @return
         *     possible object is
         *     {@link TStatementOfHolding }
         *     
         */
        public TStatementOfHolding getParticipantDestination() {
            return participantDestination;
        }

        /**
         * Sets the value of the participantDestination property.
         * 
         * @param value
         *     allowed object is
         *     {@link TStatementOfHolding }
         *     
         */
        public void setParticipantDestination(TStatementOfHolding value) {
            this.participantDestination = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ParticipantSource" type="{urn:dmt:custodian2016}TStatement_of_Transactions" minOccurs="0"/&gt;
     *         &lt;element name="ParticipantDestination" type="{urn:dmt:custodian2016}TStatement_of_Transactions" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participantSource",
        "participantDestination"
    })
    public static class StatementOfTransactions {

        @XmlElement(name = "ParticipantSource")
        protected TStatementOfTransactions participantSource;
        @XmlElement(name = "ParticipantDestination")
        protected TStatementOfTransactions participantDestination;

        /**
         * Gets the value of the participantSource property.
         * 
         * @return
         *     possible object is
         *     {@link TStatementOfTransactions }
         *     
         */
        public TStatementOfTransactions getParticipantSource() {
            return participantSource;
        }

        /**
         * Sets the value of the participantSource property.
         * 
         * @param value
         *     allowed object is
         *     {@link TStatementOfTransactions }
         *     
         */
        public void setParticipantSource(TStatementOfTransactions value) {
            this.participantSource = value;
        }

        /**
         * Gets the value of the participantDestination property.
         * 
         * @return
         *     possible object is
         *     {@link TStatementOfTransactions }
         *     
         */
        public TStatementOfTransactions getParticipantDestination() {
            return participantDestination;
        }

        /**
         * Sets the value of the participantDestination property.
         * 
         * @param value
         *     allowed object is
         *     {@link TStatementOfTransactions }
         *     
         */
        public void setParticipantDestination(TStatementOfTransactions value) {
            this.participantDestination = value;
        }

    }

}
