//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTransactionProcessing.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="TTransactionProcessing"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Auto"/&gt;
 *     &lt;enumeration value="Manual"/&gt;
 *     &lt;enumeration value="System"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TTransactionProcessing")
@XmlEnum
public enum TTransactionProcessing {


    /**
     * Транзакция выполняется автоматически. Если это не противоречит установкам ПО "Хранитель 2016" для данного типа транзакций
     * 
     */
    @XmlEnumValue("Auto")
    AUTO("Auto"),

    /**
     * Транзакция требует ручной верификации пользователя в ПО "Хранитель 2016"
     * 
     */
    @XmlEnumValue("Manual")
    MANUAL("Manual"),

    /**
     * Тип выполнения транзакции выбирается согласно настройкам ПО "Хранитель 2016"
     * 
     */
    @XmlEnumValue("System")
    SYSTEM("System");
    private final String value;

    TTransactionProcessing(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTransactionProcessing fromValue(String v) {
        for (TTransactionProcessing c: TTransactionProcessing.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
