//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.02 at 09:35:26 PM MSK 
//


package dmt.custodian2016;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTransaction_request_Reversal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTransaction_request_Reversal"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Agreement"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{urn:dmt:custodian2016}TAgreementBase"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="transaction_identity"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="RequestID" type="{urn:dmt:custodian2016}TGUID"/&gt;
 *                   &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTransaction_request_Reversal", propOrder = {
    "agreement",
    "transactionIdentity"
})
public class TTransactionRequestReversal {

    @XmlElement(name = "Agreement", required = true)
    protected TTransactionRequestReversal.Agreement agreement;
    @XmlElement(name = "transaction_identity", required = true)
    protected TTransactionRequestReversal.TransactionIdentity transactionIdentity;

    /**
     * Gets the value of the agreement property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRequestReversal.Agreement }
     *     
     */
    public TTransactionRequestReversal.Agreement getAgreement() {
        return agreement;
    }

    /**
     * Sets the value of the agreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRequestReversal.Agreement }
     *     
     */
    public void setAgreement(TTransactionRequestReversal.Agreement value) {
        this.agreement = value;
    }

    /**
     * Gets the value of the transactionIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link TTransactionRequestReversal.TransactionIdentity }
     *     
     */
    public TTransactionRequestReversal.TransactionIdentity getTransactionIdentity() {
        return transactionIdentity;
    }

    /**
     * Sets the value of the transactionIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTransactionRequestReversal.TransactionIdentity }
     *     
     */
    public void setTransactionIdentity(TTransactionRequestReversal.TransactionIdentity value) {
        this.transactionIdentity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{urn:dmt:custodian2016}TAgreementBase"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Agreement
        extends TAgreementBase
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="RequestID" type="{urn:dmt:custodian2016}TGUID"/&gt;
     *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestID",
        "orderID",
        "id"
    })
    public static class TransactionIdentity {

        @XmlElement(name = "RequestID")
        protected String requestID;
        @XmlElement(name = "OrderID")
        protected Integer orderID;
        @XmlElement(name = "ID")
        protected Integer id;

        /**
         * Gets the value of the requestID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestID() {
            return requestID;
        }

        /**
         * Sets the value of the requestID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestID(String value) {
            this.requestID = value;
        }

        /**
         * Gets the value of the orderID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getOrderID() {
            return orderID;
        }

        /**
         * Sets the value of the orderID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setOrderID(Integer value) {
            this.orderID = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setID(Integer value) {
            this.id = value;
        }

    }

}
